app = 'magictables'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  DATA_DIR = '/data'

[[mounts]]
  source = 'magictables_data'
  destination = '/data'

[[services]]
  internal_port = 80
  protocol = 'tcp'

  [[services.ports]]
    handlers = ['http']
    port = 80

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443
